title: Ping Yu # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Second-year PhD Student in CSE department at the University at Buffalo, State University of New York, supervised by Dr. Changyou Chen.
  
  <br><br>

  In general my research interest includes: 
  <br><br>
  - Deep generative models such as VAE and GAN
  - Deep reinforcement learning
  - Applications for sequence generation include text generation and action generation


  <a href="https://www.linkedin.com/in/ping-yu-05ba8212b/">View My LinkedIn Profile</a> 



  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
